### ISSUE TITLE
2.0.0 Release on PyPI

### ISSUE THREAD

**Issue by ColCarroll** [Syntaf/travis-sphinx#26]
Thanks for the useful CLI!  

Any plans to push the 2.0.x release to pypi?  [We're trying to use this](https://github.com/pymc-devs/pymc3/pull/2698), but need the `-c` flag (will install from github in the meantime).

**Comment by Syntaf** [comment]
2.0.0 should be going out to pypi soon, but I want to address #24 first. 

It seems the `--pullrequest` option was moved to the deploy command, which is wrong since the owner repo doesn't ever have access the the PR repos gh-pages branches. I wanted `--pullrequest` to exist so the owner would know if a pull request had any invalid documentation. Still deciding if I want this option anymore though.

**Comment by Syntaf** [comment]
The wonderful people over at PyPa decided to break uploading to pypi via windows, so I'll upload this sometime tomorrow when I get my linux machine up and running. Thanks for your PR

**Comment by Syntaf** [comment]
2.0.0 is out. Thanks for your help!

**Comment by ColCarroll** [comment]
Thanks for the super fast turn around and useful library!
