### ISSUE TITLE
Allow building docs in other branches than master

### ISSUE THREAD

**Issue by tomschr** [Syntaf/travis-sphinx#4]
Thanks for creating this very useful script! :+1:  After playing around with travis-sphinx, I like it very much. Much appreciated!

One issue that bothers me is that you can't build your Sphinx documentation other than from master.

For example, I use a GitFlow workflow which distinguish between master, develop, and different feature branches. I would like to have the docs build in master and develop, but not necessarily in a feature branch. 

Currently, it seems the master branch is [hard coded](https://github.com/Syntaf/travis-sphinx/blob/master/travis_sphinx.py#L41) in travis-sphinx.

It would be nice, if this could be changed -- through command line options or config files is secondary.

**Comment by Syntaf** [comment]
Agreed, it would probably be a nice option to allow people to build on other branches. 

I'm thinking I'll add a command line option, `branches` where you can specify a list of branches to run the tool with. The option will be optional and will default to `master` if not used, but otherwise the user can specify something like `--branches=master,develop,some_other_branch` which allow for the tool to work on those specified branches. 

Is that what you had in mind?

**Comment by tomschr** [comment]
> The option will be optional and will default to master if not used, but otherwise the user can specify something like --branches=master,develop,some_other_branch

That sounds great! :+1: 

> Is that what you had in mind?

Yes. :smile:

**Comment by tomschr** [comment]
Oh, I forgot to add: Would it make sense to allow some kind of "globbing" or "regular expression"?

For example, when I would like to allow building and deploying from a feature branch, the expression could be `feature/*`. That will include everything under `feature/`, but not `bugfix/`.

**Comment by Syntaf** [comment]
Sorry for the wait, impl with https://github.com/Syntaf/travis-sphinx/commit/15d4c5de62d2d754dda6da1c8697d3bb5a22c5eb . Tested and uploaded to pypi. You can now use `branches=master,something_else,test_branch` to deploy
